# Generated by Django 5.0.7 on 2025-02-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executivemeeting',
            old_name='agenda',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='booking',
            name='resource_type',
            field=models.CharField(choices=[('Room', 'Room'), ('Vehicle', 'Vehicle')], max_length=50),
        ),
    ]
