# Generated by Django 5.0.7 on 2025-02-05 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivemeeting',
            name='purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_meetings', to='bookingsystem.purpose'),
        ),
    ]
