# Generated by Django 5.1 on 2024-11-18 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0002_booking_alter_room_status_alter_vehicle_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='resource_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookingsystem.room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookingsystem.vehicle'),
        ),
    ]
