# Generated by Django 5.0.7 on 2025-01-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0002_remove_booking_total_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('driver', 'driver'), ('executive', 'executive')], default='admin', max_length=50, null=True),
        ),
    ]
