# Generated by Django 5.1.3 on 2025-02-05 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0002_executivemeeting_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookingsystem.departement'),
        ),
    ]
