# Generated by Django 5.0.7 on 2025-02-03 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0002_rename_agenda_executivemeeting_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executivemeeting',
            old_name='decision',
            new_name='obs',
        ),
        migrations.RemoveField(
            model_name='executivemeeting',
            name='invited_users',
        ),
        migrations.RemoveField(
            model_name='executivemeeting',
            name='participants',
        ),
        migrations.AddField(
            model_name='executivemeeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='meeting_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
