# Generated by Django 5.1.3 on 2025-02-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0003_booking_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
