# Generated by Django 5.0.7 on 2025-02-04 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0003_rename_decision_executivemeeting_obs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executivemeeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='meeting_participants', to='bookingsystem.departement'),
        ),
        migrations.AlterField(
            model_name='executivemeeting',
            name='requester_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Requester'),
        ),
    ]
