# Generated by Django 5.1.3 on 2025-02-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0004_booking_destination_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='description',
            new_name='travel_description',
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
