# Generated by Django 5.0.7 on 2025-02-04 01:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0004_alter_executivemeeting_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executivemeeting',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='executivemeeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='meeting_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
