# Generated by Django 5.1.3 on 2025-02-02 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0004_fcmtoken_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='resource_type',
            field=models.CharField(choices=[('Room', 'Room'), ('Vehicle', 'Vehicle'), ('Executive Meeting', 'Executive Meeting')], max_length=50),
        ),
        migrations.CreateModel(
            name='ExecutiveMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('participants', models.TextField(help_text='List of participants (separated by commas)')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_meetings', to='bookingsystem.departement')),
                ('purpose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_meetings', to='bookingsystem.purpose')),
                ('requester_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
