# Generated by Django 5.1 on 2024-11-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0004_booking_destination_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='travel_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
