# Generated by Django 5.0.7 on 2025-02-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0005_remove_executivemeeting_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executivemeeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='meeting_participants', to='bookingsystem.departement'),
        ),
    ]
