# Generated by Django 5.1.3 on 2025-02-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0005_rename_description_booking_travel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(default='No Description'),
        ),
    ]
