# Generated by Django 5.1.3 on 2025-02-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0006_booking_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='travel_description',
        ),
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.TextField(),
        ),
    ]
