# Generated by Django 4.2.16 on 2024-12-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0006_remove_booking_vehicle_type_alter_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='travel_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Van', 'Van'), ('Truck', 'Truck')], max_length=50),
        ),
    ]
