# Generated by Django 5.0.7 on 2025-02-04 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0006_alter_executivemeeting_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivemeeting',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_meetings', to='bookingsystem.room'),
        ),
        migrations.AddField(
            model_name='executivemeeting',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_meetings', to='bookingsystem.vehicle'),
        ),
    ]
