# Generated by Django 5.0.7 on 2024-12-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0007_alter_booking_travel_description_alter_vehicle_type'),
        ('bookingsystem', '0007_driver_alter_vehicle_type_vehicle_driver'),
    ]

    operations = [
    ]
