# Generated by Django 5.0.7 on 2024-12-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0008_merge_20241203_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='travel_description',
        ),
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(default='General Description'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination_address',
            field=models.CharField(max_length=255),
        ),
    ]
