# Generated by Django 5.0.7 on 2025-02-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0008_alter_executivemeeting_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executivemeeting',
            name='location',
            field=models.CharField(default='Default Location', max_length=255),
        ),
    ]
