# Generated by Django 5.0.7 on 2024-12-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0009_remove_booking_travel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination_address',
            field=models.CharField(default='Default Address', max_length=255),
        ),
    ]
