# Generated by Django 5.0.7 on 2024-12-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0010_alter_booking_destination_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.TextField(),
        ),
    ]
