# Generated by Django 5.0.7 on 2024-12-04 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0011_alter_booking_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='description',
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookingsystem.vehicle'),
        ),
    ]
