# Generated by Django 5.0.7 on 2024-12-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0013_departement_alter_booking_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='travel_description',
            field=models.TextField(),
        ),
    ]
