# Generated by Django 5.0.7 on 2024-12-05 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0014_alter_booking_travel_description'),
    ]

    operations = [
    ]
